apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: projected-resource-csi-driver.openshift.io
spec:
  # Supports ephemeral inline volumes.
  volumeLifecycleModes:
  #- Persistent
  - Ephemeral
  # To determine at runtime which mode a volume uses, pod info and its
  # "csi.storage.k8s.io/ephemeral" entry are needed.
  podInfoOnMount: true
